name: Deploy to AWS

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Deploy to AWS EC2 via SSH
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.AWS_HOST }}
                  username: ${{ secrets.AWS_USER }}
                  key: ${{ secrets.AWS_SSH_KEY }}
                  script: |
                      cd /home/ubuntu/devops-assessment
                      chmod +x deployment/deploy.sh
                      ./deployment/deploy.sh
